// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type Flight = {
  departureLocation: string;
  arrivalLocation: string;
  departureTime: string;
  arrivalTime: string;
  company: string;
  price: number;
  totalTime: string;
};

export type Location = {
  id: string;
  code: string;
  city: string;
  country: string;
  state?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  isPopular?: boolean;
};

export type User = {
  username: string;
  email: string;
  password: string;
};

export interface CurrentUser {
  id: string;
  username: string;
  email: string;
}

export interface CurrentUserQueryData {
  me?: CurrentUser | null;
}

// Hotel API Types
export interface AccessibilityAttributes {
  attributes?: string[] | null;
  showerChair?: boolean | null;
  entranceType?: string | null;
  petFriendly?: string | null;
  rampAngle?: number | null;
  rampLength?: number | null;
  entranceDoorWidth?: number | null;
  roomMaxGuestsNumber?: number | null;
  distanceFromTheElevatorToTheAccessibleRoom?: number | null;
}

export interface Hotel {
  id: string;
  name: string;
  hotelDescription?: string | null;
  hotelTypeId?: number | null;
  chain?: string | null;
  currency?: string | null;
  location: string;
  country?: string | null;
  city?: string | null;
  address?: string | null;
  zip?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  pricePerNight: number;
  rating?: number | null;
  reviewCount?: number | null;
  isAvailable: boolean;
  image?: string | null;
  mainPhoto?: string | null;
  thumbnail?: string | null;
  stars?: number | null;
  facilityIds?: number[] | null;
  accessibilityAttributes?: AccessibilityAttributes | null;
  deletedAt?: string | null;
}

export interface SearchHotelsByLocationData {
  hotelsByLocation: Hotel[];
}

export interface TopHotelsData {
  popularHotels: Hotel[];
}

export interface Booking {
  id: string;
  userId: string;
  hotelId: string;
  firstNameGuest: string;
  lastNameGuest: string;
  emailGuest: string;
  phoneNumberGuest: string | null;
  startTime: string;
  endTime: string;
  status: string;
  price: number | null;
  currency: string | null;
  createdAt: string;
  confirmedAt?: string | null;
  canceledAt?: string | null;
}

export interface CreateBookingMutationData {
  createBooking: Booking;
}

export interface BookingsByUserEmailData {
  bookingsByUserEmail: Booking[];
}

export interface HotelByIdData {
  hotelById: Hotel;
}

export interface HotelCreateDtoInput {
  id?: string | null;
  name: string;
  location: string;
  image?: string | null;
  isAvailable?: boolean | null;
  rating?: number | null;
  reviewCount?: number | null;
  pricePerNight: number;
  latitude?: number | null;
  longitude?: number | null;
  hotelDescription?: string | null;
  hotelTypeId?: number | null;
  chain?: string | null;
  currency?: string | null;
  country?: string | null;
  city?: string | null;
  address?: string | null;
  zip?: string | null;
  mainPhoto?: string | null;
  thumbnail?: string | null;
  stars?: number | null;
  facilityIds?: number[] | null;
  accessibilityAttributes?: AccessibilityAttributes | null;
  deletedAt?: string | null;
}

export interface CreateHotelMutationData {
  createHotel: Hotel;
}
