/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetLocations {\n    locations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n    }\n  }\n": typeof types.GetLocationsDocument,
    "\n  query topLocations {\n    topLocations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n      isPopular\n    }\n  }\n": typeof types.TopLocationsDocument,
    "\n  mutation Login($authRequest: AuthInput!) {\n    login(authRequest: $authRequest) {\n      token\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation RegisterUser($userRegistrationDto: UserRegistrationInput!) {\n    registerUser(userRegistrationDto: $userRegistrationDto) {\n      id\n      username\n      email\n    }\n  }\n": typeof types.RegisterUserDocument,
    "\n  mutation ForgotPassword($email: String!) {\n    forgotPassword(email: $email) {\n      success\n      message\n    }\n  }\n": typeof types.ForgotPasswordDocument,
    "\n  mutation ResetPassword($email: String!, $token: String!, $newPassword: String!) {\n    resetPassword(email: $email, token: $token, newPassword: $newPassword) {\n      success\n      message\n    }\n  }\n": typeof types.ResetPasswordDocument,
    "\n  mutation Logout {\n    logout\n  }\n": typeof types.LogoutDocument,
    "\n  query SendMessage($message: String!) {\n    sendMessage(message: $message) {\n      success\n      chatResponseType\n      searchData {\n        id\n        name\n        location\n        image\n        isAvailable\n        rating\n        reviewCount\n        pricePerNight\n        latitude\n        longitude\n        hotelDescription\n        hotelTypeId\n        chain\n        currency\n        country\n        city\n        address\n        zip\n        mainPhoto\n        thumbnail\n        stars\n      }\n      questionData\n      otherData\n      bookingData\n      errorData\n    }\n  }\n": typeof types.SendMessageDocument,
    "\n  query CurrentUser {\n    me {\n      id\n      username\n      email\n    }\n  }\n": typeof types.CurrentUserDocument,
    "\n  mutation CreateBooking($bookingCreateDto: BookingCreateInput!) {\n    createBooking(bookingCreateDto: $bookingCreateDto) {\n      id\n      userId\n      hotelId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n": typeof types.CreateBookingDocument,
    "\n  mutation CreateHotel($hotelCreateDto: HotelCreateInput!) {\n    createHotel(hotelCreateDto: $hotelCreateDto) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": typeof types.CreateHotelDocument,
    "\n  query BookingsByUserEmail($email: String!) {\n    bookingsByUserEmail(email: $email) {\n      id\n      hotelId\n      userId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n": typeof types.BookingsByUserEmailDocument,
    "\n  query HotelById($id: ID!) {\n    hotelById(id: $id) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": typeof types.HotelByIdDocument,
    "\n  query GET_HOTELS {\n    hotels {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n    }\n  }\n": typeof types.Get_HotelsDocument,
    "\n  query GetHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n    }\n  }\n": typeof types.GetHotelsByLocationDocument,
    "\n  query searchHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": typeof types.SearchHotelsByLocationDocument,
    "\n  query TopHotels {\n    popularHotels {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": typeof types.TopHotelsDocument,
};
const documents: Documents = {
    "\n  query GetLocations {\n    locations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n    }\n  }\n": types.GetLocationsDocument,
    "\n  query topLocations {\n    topLocations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n      isPopular\n    }\n  }\n": types.TopLocationsDocument,
    "\n  mutation Login($authRequest: AuthInput!) {\n    login(authRequest: $authRequest) {\n      token\n    }\n  }\n": types.LoginDocument,
    "\n  mutation RegisterUser($userRegistrationDto: UserRegistrationInput!) {\n    registerUser(userRegistrationDto: $userRegistrationDto) {\n      id\n      username\n      email\n    }\n  }\n": types.RegisterUserDocument,
    "\n  mutation ForgotPassword($email: String!) {\n    forgotPassword(email: $email) {\n      success\n      message\n    }\n  }\n": types.ForgotPasswordDocument,
    "\n  mutation ResetPassword($email: String!, $token: String!, $newPassword: String!) {\n    resetPassword(email: $email, token: $token, newPassword: $newPassword) {\n      success\n      message\n    }\n  }\n": types.ResetPasswordDocument,
    "\n  mutation Logout {\n    logout\n  }\n": types.LogoutDocument,
    "\n  query SendMessage($message: String!) {\n    sendMessage(message: $message) {\n      success\n      chatResponseType\n      searchData {\n        id\n        name\n        location\n        image\n        isAvailable\n        rating\n        reviewCount\n        pricePerNight\n        latitude\n        longitude\n        hotelDescription\n        hotelTypeId\n        chain\n        currency\n        country\n        city\n        address\n        zip\n        mainPhoto\n        thumbnail\n        stars\n      }\n      questionData\n      otherData\n      bookingData\n      errorData\n    }\n  }\n": types.SendMessageDocument,
    "\n  query CurrentUser {\n    me {\n      id\n      username\n      email\n    }\n  }\n": types.CurrentUserDocument,
    "\n  mutation CreateBooking($bookingCreateDto: BookingCreateInput!) {\n    createBooking(bookingCreateDto: $bookingCreateDto) {\n      id\n      userId\n      hotelId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n": types.CreateBookingDocument,
    "\n  mutation CreateHotel($hotelCreateDto: HotelCreateInput!) {\n    createHotel(hotelCreateDto: $hotelCreateDto) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": types.CreateHotelDocument,
    "\n  query BookingsByUserEmail($email: String!) {\n    bookingsByUserEmail(email: $email) {\n      id\n      hotelId\n      userId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n": types.BookingsByUserEmailDocument,
    "\n  query HotelById($id: ID!) {\n    hotelById(id: $id) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": types.HotelByIdDocument,
    "\n  query GET_HOTELS {\n    hotels {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n    }\n  }\n": types.Get_HotelsDocument,
    "\n  query GetHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n    }\n  }\n": types.GetHotelsByLocationDocument,
    "\n  query searchHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": types.SearchHotelsByLocationDocument,
    "\n  query TopHotels {\n    popularHotels {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n": types.TopHotelsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLocations {\n    locations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n    }\n  }\n"): (typeof documents)["\n  query GetLocations {\n    locations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query topLocations {\n    topLocations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n      isPopular\n    }\n  }\n"): (typeof documents)["\n  query topLocations {\n    topLocations {\n      id\n      code\n      city\n      country\n      state\n      latitude\n      longitude\n      isPopular\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Login($authRequest: AuthInput!) {\n    login(authRequest: $authRequest) {\n      token\n    }\n  }\n"): (typeof documents)["\n  mutation Login($authRequest: AuthInput!) {\n    login(authRequest: $authRequest) {\n      token\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegisterUser($userRegistrationDto: UserRegistrationInput!) {\n    registerUser(userRegistrationDto: $userRegistrationDto) {\n      id\n      username\n      email\n    }\n  }\n"): (typeof documents)["\n  mutation RegisterUser($userRegistrationDto: UserRegistrationInput!) {\n    registerUser(userRegistrationDto: $userRegistrationDto) {\n      id\n      username\n      email\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ForgotPassword($email: String!) {\n    forgotPassword(email: $email) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ForgotPassword($email: String!) {\n    forgotPassword(email: $email) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResetPassword($email: String!, $token: String!, $newPassword: String!) {\n    resetPassword(email: $email, token: $token, newPassword: $newPassword) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ResetPassword($email: String!, $token: String!, $newPassword: String!) {\n    resetPassword(email: $email, token: $token, newPassword: $newPassword) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Logout {\n    logout\n  }\n"): (typeof documents)["\n  mutation Logout {\n    logout\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SendMessage($message: String!) {\n    sendMessage(message: $message) {\n      success\n      chatResponseType\n      searchData {\n        id\n        name\n        location\n        image\n        isAvailable\n        rating\n        reviewCount\n        pricePerNight\n        latitude\n        longitude\n        hotelDescription\n        hotelTypeId\n        chain\n        currency\n        country\n        city\n        address\n        zip\n        mainPhoto\n        thumbnail\n        stars\n      }\n      questionData\n      otherData\n      bookingData\n      errorData\n    }\n  }\n"): (typeof documents)["\n  query SendMessage($message: String!) {\n    sendMessage(message: $message) {\n      success\n      chatResponseType\n      searchData {\n        id\n        name\n        location\n        image\n        isAvailable\n        rating\n        reviewCount\n        pricePerNight\n        latitude\n        longitude\n        hotelDescription\n        hotelTypeId\n        chain\n        currency\n        country\n        city\n        address\n        zip\n        mainPhoto\n        thumbnail\n        stars\n      }\n      questionData\n      otherData\n      bookingData\n      errorData\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CurrentUser {\n    me {\n      id\n      username\n      email\n    }\n  }\n"): (typeof documents)["\n  query CurrentUser {\n    me {\n      id\n      username\n      email\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateBooking($bookingCreateDto: BookingCreateInput!) {\n    createBooking(bookingCreateDto: $bookingCreateDto) {\n      id\n      userId\n      hotelId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateBooking($bookingCreateDto: BookingCreateInput!) {\n    createBooking(bookingCreateDto: $bookingCreateDto) {\n      id\n      userId\n      hotelId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateHotel($hotelCreateDto: HotelCreateInput!) {\n    createHotel(hotelCreateDto: $hotelCreateDto) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateHotel($hotelCreateDto: HotelCreateInput!) {\n    createHotel(hotelCreateDto: $hotelCreateDto) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query BookingsByUserEmail($email: String!) {\n    bookingsByUserEmail(email: $email) {\n      id\n      hotelId\n      userId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n"): (typeof documents)["\n  query BookingsByUserEmail($email: String!) {\n    bookingsByUserEmail(email: $email) {\n      id\n      hotelId\n      userId\n      firstNameGuest\n      lastNameGuest\n      emailGuest\n      phoneNumberGuest\n      startTime\n      endTime\n      status\n      price\n      currency\n      createdAt\n      confirmedAt\n      canceledAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query HotelById($id: ID!) {\n    hotelById(id: $id) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  query HotelById($id: ID!) {\n    hotelById(id: $id) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GET_HOTELS {\n    hotels {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n    }\n  }\n"): (typeof documents)["\n  query GET_HOTELS {\n    hotels {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      country\n      city\n      address\n      zip\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n    }\n  }\n"): (typeof documents)["\n  query GetHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      location\n      image\n      isAvailable\n      rating\n      reviewCount\n      pricePerNight\n      latitude\n      longitude\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query searchHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  query searchHotelsByLocation($location: String!) {\n    hotelsByLocation(location: $location) {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TopHotels {\n    popularHotels {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  query TopHotels {\n    popularHotels {\n      id\n      name\n      hotelDescription\n      hotelTypeId\n      chain\n      currency\n      location\n      country\n      city\n      address\n      zip\n      latitude\n      longitude\n      pricePerNight\n      rating\n      reviewCount\n      isAvailable\n      image\n      mainPhoto\n      thumbnail\n      stars\n      facilityIds\n      accessibilityAttributes {\n        attributes\n        showerChair\n        entranceType\n        petFriendly\n        rampAngle\n        rampLength\n        entranceDoorWidth\n        roomMaxGuestsNumber\n        distanceFromTheElevatorToTheAccessibleRoom\n      }\n      deletedAt\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;